apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
    name: bob-csr
spec:
    groups:
        - system:authenticated
    request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1pUQ0NBVTBDQVFBd0lERU1NQW9HQTFVRUF3d0RZbTlpTVJBd0RnWURWUVFLREFkc1pXRnlibVZ5TUlJQgpJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBNTAwWlI1VUozVGlJTVZPbVgvNXRUNWxqCm55ZGRIbUJGdXhUWjZPc3c0R0dUbkIyR0FoMlIzbkFCU1lYajdZWnlDelRDWURkSXhQUmhQNHdhQUdzY1kwT1IKYWNKZ3l2VDlUck9qN3dzSjVENG1ZSVVOU0VKdzZzMkNWUVdqOGsyVDlpWWxXSy9SaVd1WGZseXphTm5zdDVGWQo0dmVDM2hjZnVucHBmZWhwTHRMaW9sNi9aN25MRmZrK3ZjclY0cTc4TlZIT1liMng2ckZ2dVFkUmc5K2VPcjFMClBmUU9aTzZQSlZ4YkRBUDBxWXBGeHpybzJBNlp3Q3A4dlIwZnZEcGplMnN4TFU3SDdtbE5QMjcwb21DNnlEMSsKaTNTK3VQV3hGRjRYS3Z6UCtiMitoai9LNnA4dCtrYTkzZS9EQzhBM0dueFUyS09hK2JkRVh0VVVFbU5Oc3dJRApBUUFCb0FBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFPYWxTcExoNnFmWkw5QjlpWGtBQkJaeTA1TVVOcjJtCldvdnVWV3JpWnZxV2pRT1JYNGRVTW5raVprbzgyRFptNXV4aGxKZWJnY2ljd0laWHZNNkhicUtzdGhheGlWcFcKdnF0N3BvcGpXaFBlSmtGV3JoN1lEK29XM29KMlNpRVcwYWdFRWNRWU81cVc3Ujl4TDdNMTl1UFhmdVdrQ0xCYgowdDloMkVrUVl3RnFGYjNUUlJTWVdvcEcycTZsZVRINkxDdUIzRGZET3NtTWlVUWdlbVZYUkZCUTFPQlFEOUpqCmNlVldIbFE4S0hvNjhlcnFOM0RRVm1zMzRMeXVqQWRmd284TDl3czdnbGZqdDBFNS9zS2NrZlJoRmRQVDErTjIKLzJyTXdqOVJ6NEdtcDhKUFBwNC9tNXdKK2hyYjBiKzhmK1daZmhCaHZZOU5OZ3FIdFJ2c1pnYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
    signerName: kubernetes.io/kube-apiserver-client
    usages:
        - digital signature
        - key encipherment
        - client auth
